# Generated by Django 4.2.23 on 2025-08-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                ("logo", models.ImageField(upload_to="", verbose_name="logo图片")),
                (
                    "first_letter",
                    models.CharField(max_length=1, verbose_name="品牌首字母"),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "db_table": "tb_brand",
            },
        ),
        migrations.CreateModel(
            name="GoodsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=10)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": ("商品类别",),
                "verbose_name_plural": ("商品类别",),
                "db_table": "tb_goods_category",
            },
        ),
        migrations.CreateModel(
            name="GoodsChannelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "商品频道组",
                "verbose_name_plural": "商品频道组",
                "db_table": "tb_channel_group",
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("caption", models.CharField(max_length=100, verbose_name="副标题")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="进价"
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="市场价"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                ("sales", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                (
                    "is_launched",
                    models.BooleanField(default=True, verbose_name="是否上架销售"),
                ),
                (
                    "default_image",
                    models.ImageField(
                        blank=True, default="", max_length=200, null=True, upload_to=""
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="goods.goodscategory",
                        verbose_name="从属类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品sku",
                "verbose_name_plural": "商品sku",
                "db_table": "tb_sku",
            },
        ),
        migrations.CreateModel(
            name="SPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("sales", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("desc_detail", models.TextField(default="", verbose_name="详细介绍")),
                ("desc_pack", models.TextField(default="", verbose_name="包装信息")),
                ("desc_service", models.TextField(default="", verbose_name="售后服务")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="goods.brand"
                    ),
                ),
                (
                    "category1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cat1_spu",
                        to="goods.goodscategory",
                        verbose_name="从属类别1",
                    ),
                ),
                (
                    "category2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cat2_spu",
                        to="goods.goodscategory",
                        verbose_name="从属类别2",
                    ),
                ),
                (
                    "category3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cat3_spu",
                        to="goods.goodscategory",
                        verbose_name="从属类别3",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品spu",
                "verbose_name_plural": "商品spu",
                "db_table": "tb_spu",
            },
        ),
        migrations.CreateModel(
            name="SPUSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "spu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="goods.spu",
                        verbose_name="商品spu",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品spu规格",
                "verbose_name_plural": "商品spu规格",
                "db_table": "tb_spu_specification",
            },
        ),
        migrations.CreateModel(
            name="SpecificationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=20, verbose_name="选项值")),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="goods.spuspecification",
                    ),
                ),
            ],
            options={
                "verbose_name": "规格选项",
                "verbose_name_plural": "规格选项",
                "db_table": "tb_specification_option",
            },
        ),
        migrations.CreateModel(
            name="SKUSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="goods.specificationoption",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="goods.sku",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="goods.spuspecification",
                    ),
                ),
            ],
            options={
                "verbose_name": "sku规格",
                "verbose_name_plural": "sku规格",
                "db_table": "tb_sku_specification",
            },
        ),
        migrations.CreateModel(
            name="SKUImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.sku"
                    ),
                ),
            ],
            options={
                "verbose_name": "sku图片",
                "verbose_name_plural": "sku图片",
                "db_table": "tb_sku_image",
            },
        ),
        migrations.AddField(
            model_name="sku",
            name="spu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.spu",
                verbose_name="商品",
            ),
        ),
        migrations.CreateModel(
            name="GoodsChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=200, verbose_name="频道页面链接")),
                ("sequence", models.IntegerField(verbose_name="组内顺序")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodscategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodschannelgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品频道",
                "verbose_name_plural": "商品频道",
                "db_table": "tb_goods_channel",
            },
        ),
    ]
