# Generated by Django 4.2.23 on 2025-08-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skuspecification",
            name="spec",
        ),
    ]
