# Generated by Django 4.2.23 on 2025-08-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sku",
            name="category",
        ),
        migrations.AddField(
            model_name="sku",
            name="url",
            field=models.CharField(default="", max_length=200, verbose_name="商品链接"),
        ),
        migrations.AlterField(
            model_name="goodscategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subs",
                to="goods.goodscategory",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="spu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.spu",
                verbose_name="类别",
            ),
        ),
    ]
