# Generated by Django 4.2.23 on 2025-08-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=200)),
                ("sequence", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True, verbose_name="是否展示")),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.sku"
                    ),
                ),
            ],
            options={
                "verbose_name": "快讯",
                "verbose_name_plural": "快讯",
                "db_table": "tb_flash_new",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.BooleanField(default=True, verbose_name="是否展示")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="goods.skuimage"
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "db_table": "tb_banner",
            },
        ),
    ]
