# Generated by Django 4.2.23 on 2025-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_active",
            field=models.BooleanField(default=False),
        ),
    ]
