# Generated by Django 4.2.23 on 2025-08-18 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        ("users", "0004_user_email_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receiver", models.CharField(max_length=50)),
                ("specific_address", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=11, verbose_name="手机")),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        null=True,
                        verbose_name="固定电话",
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="areas.area",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="areas.area",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provinces",
                        to="areas.area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户地址",
                "verbose_name_plural": "用户地址",
                "db_table": "tb_addresses",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="default_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.address",
            ),
        ),
    ]
