# Generated by Django 4.2.23 on 2025-08-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_address_user_default_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="specific_address",
            new_name="place",
        ),
        migrations.AddField(
            model_name="address",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
